export const CREATE_COURSE = 'CREATE_COURSE';
export const DELETE_LAST_COURSE = 'DELETE_LAST_COURSE';
export const DELETE_ALL_COURSES = 'DELETE_ALL_COURSES';
export const CREATE_USER = 'CREATE_USER';
export const LOAD_COURSES_SUCCES = 'LOAD_COURSES_SUCCES';
export const LOAD_AUTHORS_SUCCES = 'LOAD_AUTHORS_SUCCES';
export const CREATE_COURSE_SUCCES = 'CREATE_COURSE_SUCCES';
export const UPDATE_COURSE_SUCCES = 'UPDATE_COURSE_SUCCES';